#!/usr/bin/env bash
# Installs nginx on server web-01
# server listens on port 80
# returns a page with string hello world
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /usr/share/nginx/html/index
sudo service nginx start
